### ISSUE TITLE
Deal with typos in the wards (from legislation!)

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/EveryElection#40]
- [ ] Dorset - Broadway - should be Broadwey
- [ ] East Renfrewshire - Newton Means North and Neilston - should be Newton Mearns North and Neilston
- [ ] Falkirk - Boâness and Blackness - should be Bo'ness and Blackness
- [ ] Highland - Eilean aâ² ChÃ¨o - should be Eilean a' Cheò (according to the SOPN anyway - spelling seems to be variable)
- [ ] Rhondda Cynon Taff - should be Rhondda Cynon Taf (council uses the same in both Welsh and English)

Not a 'uuuge priority.

**Comment by chris48s** [comment]
More widely, solve "The Sklemersdale problem"

It should be possible for `local.lancashire.skelmersdale-east.2017-05-04` and `local.lancashire.sklemersdale-east.2017-05-04` to point to the same election record.

Implementation details to be decided

**Comment by chris48s** [comment]
Another potential use-case for being able to assign more than one human-readable ID strings to a single election object is creating bilingual election ids. For example, it might be useful for both `local.cardiff.date` and `lleol.cardydd.date` to point to the same election object.

Obviously the motivation for that is different, but the modifications to the data structure would be the same and support both cases.

**Comment by chris48s** [comment]
There's a couple of these where I've fixed the names in the process of attaching GSS codes:

* https://elections.democracyclub.org.uk/admin/organisations/organisationdivision/25423/change
* https://elections.democracyclub.org.uk/admin/organisations/organisationdivision/25507/change

but I haven't changed the slugs because we've already created id using the incorrect slugs:

* https://elections.democracyclub.org.uk/elections/local.east-renfrewshire.newton-means-north-and-neilston.2017-05-04/
* https://elections.democracyclub.org.uk/elections/local.highland.eilean-aa2-cha-o.2017-05-04/

What is the impact of also updating the slugs at this point?

**Comment by sjorford** [comment]
Spotted this one: https://candidates.democracyclub.org.uk/elections/local.somerset.mendip-hiils.2017-05-04/

"Mendip Hills" in https://www.legislation.gov.uk/uksi/2012/2984/made
"Mendip Hiils" in https://data.gov.uk/dataset/b301ade6-8b5e-4134-86fa-eca9c432faf7/county-electoral-division-may-2019-names-and-codes-for-england

**Comment by GeoWill** [comment]
Some `Divisions` have had their names (and slugs and official identifiers) fixed ahead of the 2021 elections. These were:
- ~Pinhow~ Pinhoe and Mincinglake
- ~Sklemersdale~ Skelmersdale East 
- Castle ~Donnington~ Donington & Kegworth

This means there are some old elections whose `election_id` doesn't match the `slug` on the division. These need more work, as the ids will be in use in YNR. 
```
>>> Election.public_objects.exclude(election_id__contains=F("division__slug"))
<ElectionQuerySet [<Election: local.devon.pinhow-mincinglake.2017-05-04>, <Election: local.hampshire.chandleras-ford.2017-05-04>, <Election: local.highland.eilean-aa2-cha-o.2017-05-04>, <Election: local.leicestershire.castle-donnington-kegworth.2017-05-04>, <Election: local.somerset.mendip-hiils.2017-05-04>]>
```

**Comment by sjorford** [comment]
Rhondda Cynon Taf(f) is still wrong - I created the by-election IDs for 6th May before I spotted this
https://elections.democracyclub.org.uk/elections/local.rhondda-cynon-taff.2021-05-06/

**Comment by pmk01** [comment]
Dorset: Colehill East and Staphill, should be Stapehill
https://www.legislation.gov.uk/uksi/2016/64/pdfs/uksics_20160064_en.pdf
